### ISSUE TITLE
False color display

### ISSUE THREAD

**Issue by Red-edge** [ChangeClock/RobomasterSimulator#6]
- [ ] #7
- [ ] #8

![image](https://github.com/ChangeClock/RobomasterSimulator/assets/118868872/97dd0d08-1b37-4340-a7e4-e291b2e6e72d)
![image](https://github.com/ChangeClock/RobomasterSimulator/assets/118868872/08477bc8-abee-4fff-81fd-d458cd4e59d6)

**Comment by ChangeClock** [comment]
Converted to seperated issues, closed.
